name: CI
 
on:
	push:
	    branches: [ main ]
	pull_request:
	    branches: [ main ]
 
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install and run xcodegen
      run: |
		echo "my name is alexy"
	  	# brew install fastlane
	  	#         brew install xcodegen
	  	#         xcodegen generate
	  	#     - name: Run fastlane setup
	  	#       env:
	  	#         APPLE_ACCOUNT: ${{ secrets.APPLE_ACCOUNT }}
	  	#         TEAM_ID: ${{ secrets.TEAM_ID }}
	  	#       run: |
	  	#         fastlane setup --verbose
	  	#     - name: Run fastlane build
	  	#       run: |
	  	#         fastlane compile --verbose
  