name: CI
 
on:
	push:
	  branches: [ main ]
	pull_request:
    branches: [ main ]
  
    workflow_dispatch:
  
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install and run xcodegen
      run: |
		echo "my name is alexy"
